In [1]:
import pandas as pd

In [3]:
import numpy as np

In [8]:
quantidade_palavras = np.random.randint(50, 100, 5)
quantidade_palavras

array([87, 65, 82, 74, 65], dtype=int32)

In [11]:
indices = [ "documento 1", "documento 2", "documento 3", "documento 4", "documento 5" ]

In [12]:
nova_serie = pd.Series(quantidade_palavras, index=indices)
nova_serie

documento 1    87
documento 2    65
documento 3    82
documento 4    74
documento 5    65
dtype: int32

In [13]:
nova_serie["documento 4"]

np.int32(74)

In [16]:
quantidade_palavras = np.random.randint(50, 100, 5)
indices = [ "documento 1", "documento 2", "documento 3", "documento 4", "documento 5" ]

In [21]:
quantidade_palavras

array([78, 58, 85, 77, 57], dtype=int32)

In [65]:
palavras_unicas = (quantidade_palavras * np.random.random(5)).astype(np.int32)
# palavras_unicas = np.concat([quantidade_palavras, [4]])
palavras_unicas

array([ 4, 21, 55, 40, 39], dtype=int32)

In [67]:
# df = pd.DataFrame({"quantidade palavras": quantidade_palavras, "palavras unicas": palavras_unicas}, index=indices)
df = pd.DataFrame({"quantidade palavras": quantidade_palavras, "palavras unicas": palavras_unicas})
# serie1 = pd.Series( quantidade_palavras )
# serie2 = pd.Series( palavras_unicas )
# df = pd.DataFrame({"quantidade palavras": quantidade_palavras, "palavras unicas": palavras_unicas})
df

,quantidade palavras,palavras unicas
0,78,4
1,58,21
2,85,55
3,77,40
4,57,39


In [44]:
df.loc["documento 3"]["quantidade palavras"]

np.int32(85)

In [52]:
df.iloc[4]["palavras unicas"]

np.int32(19)

In [55]:
df["quantidade palavras"].loc["documento 3"]

np.int32(85)

In [56]:
df["quantidade palavras"].iloc[3]

np.int32(77)

In [68]:
df["riqueza lexical"] = df["palavras unicas"] / df["quantidade palavras"]
df

,quantidade palavras,palavras unicas,riqueza lexical
0,78,4,0.051282
1,58,21,0.362069
2,85,55,0.647059
3,77,40,0.519481
4,57,39,0.684211


In [73]:
df = pd.DataFrame.from_dict({"quantidade palavras": quantidade_palavras, "palavras unicas": palavras_unicas}, orient="index")
df

,0,1,2,3,4
quantidade palavras,78,58,85,77,57
palavras unicas,4,21,55,40,39


In [75]:
df = pd.read_csv("C:\\git\\dados\\nlp\\analise_sentimento_portugues.csv", sep=",", encoding="utf-8")
df

,sentimento,paragrafo
0,positivo,Hoje o dia está ensolarado e perfeito para um ...
1,negativo,"Infelizmente, o ônibus atrasou e cheguei tarde..."
2,neutro,O café na cozinha acabou e preciso comprar mais.
3,positivo,Recebi uma promoção no trabalho e estou muito ...
4,negativo,Perdi meu celular e estou me sentindo frustrado.
5,neutro,O jantar foi servido às sete da noite como de ...
6,positivo,Passei no exame final e agora posso me formar.
7,negativo,A chuva forte causou muitos transtornos no trâ...
8,neutro,A reunião foi agendada para a próxima quarta-f...
9,positivo,Ganhei um presente maravilhoso de aniversário ...


In [83]:
df["sentimento"][df["sentimento"] == "positivo"]

0     positivo
3     positivo
6     positivo
9     positivo
12    positivo
15    positivo
18    positivo
21    positivo
24    positivo
27    positivo
Name: sentimento, dtype: str

In [87]:
df["sentimento numero"] = df[df["sentimento"] == "positivo"]

ValueError: Cannot set a DataFrame with multiple columns to the single column sentimento numero

In [88]:
df.head()

,sentimento,paragrafo
0,positivo,Hoje o dia está ensolarado e perfeito para um ...
1,negativo,"Infelizmente, o ônibus atrasou e cheguei tarde..."
2,neutro,O café na cozinha acabou e preciso comprar mais.
3,positivo,Recebi uma promoção no trabalho e estou muito ...
4,negativo,Perdi meu celular e estou me sentindo frustrado.


In [89]:
df.tail()

,sentimento,paragrafo
25,negativo,Perdi meu voo e agora preciso esperar pelo pró...
26,neutro,O relatório foi enviado para revisão ontem à t...
27,positivo,A performance no teatro foi incrível e cheia d...
28,negativo,Estou decepcionado com o resultado do jogo de ...
29,neutro,O ônibus passa a cada meia hora durante o dia.


In [90]:
df.describe()

,sentimento,paragrafo
count,30,30
unique,3,30
top,positivo,Hoje o dia está ensolarado e perfeito para um ...
freq,10,1


AttributeError: 'DataFrame' object has no attribute 'detail'